[workspace]
authors = ["Guilherme Leobas <guilhermeleobas@gmail.com>"]
channels = ["conda-forge"]
name = "this-week"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
collect = "bash scripts/collect.sh"

[dependencies]
hugo = ">=0.164.0,<0.165"
python = ">=3.14.6,<3.15"
